### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Daksh-jha**

### CODE REVIEW

**Review by garvitraj — APPROVED** [review]

**Comment by garvitraj** [comment]
@Daksh-jha thanks for the Updating
join our discord server and be the part of team

**Comment by Daksh-jha** [comment]
Yes sir , I want to be part of the team . How I can join your team?

I also want to ask can I apply in WOC 2.0 for this project, for which can
you please tell me what type of idea should I bring as of I am not getting
what the project is about ?

Please share the discord link and reply me soon regarding WOC so that I can
submit proposal.
Thanks in advance !
DAKSH

**Comment by garvitraj** [comment]
@Daksh-jha see the readme we have updated the discord link.
And for woc our project got down but we r trying to get it back.

Go through the read me and see the repo content you will have clear idea about it.

**Comment by Daksh-jha** [comment]
Thanks, I'll check it out.

**Pull request merged**
